### ISSUE TITLE
EditMessageAttachments doesn't work

### ISSUE THREAD

**Issue by Cyenia** [fedeericodl/replugged-plugins#2]
I can't add any more attachments. I don't know how long the problem has existed. I only noticed it yesterday.

This is the console log I get:
![image](https://github.com/FedeIlLeone/replugged-plugins/assets/35280763/b907cf21-462b-4b88-a936-674d2b78b88f)

**Comment by fedeericodl** [comment]
It's a Replugged bug which has already been fixed, but unfortunately a new patch hasn't been released yet. As soon as it is released the plugin will work normally again.
